### ISSUE TITLE
It is translating i18n variables

### ISSUE THREAD

**Issue by n00el** [taahamahdi/i18n-ai-translate#139]
Maybe we can add a line to the promt to do not touch the content between a **{{ }}** tag, but now, it is translating i18n variables and broke the translation

My command:
npx i18n-ai-translate translate -i "en.json" -o "sl.json" -e "**chatgpt**" -m "**gpt-3.5-turbo**" -k "

Original english json:
```
"categoryItems": "Items of {{category}}",
```

AI translated (hungarian)
```
"categoryItems": "{{kategória}} elemek",
```

Edit: sometimes its working, but out of 11 translations only 7 has the original {{category}}

AI translated (romanian)
```
"categoryItems": "Elemente din {{category}}",
```

btw, amazing project

**Comment by taahamahdi** [comment]
This was a pretty critical bug, thanks for finding it! Should be fixed with above PR. Please let me know if you encounter any other bugs, thanks again for using the library :)
